jandamm/zgenom

zgen.zsh

Closes https://github.com/tarjoilija/zgen/pull/125

Update official oh my zsh repo

---

.gitignore
zgen.zsh
zgenom.zsh

Closes https://github.com/tarjoilija/zgen/issues/92
Closes https://github.com/tarjoilija/zgen/issues/46

Add support for lazy loading zgen

---

_zgen
zgen.zsh

Closes https://github.com/tarjoilija/zgen/issues/122

Add zgen bin command

---

zgen.zsh

Closes https://github.com/tarjoilija/zgen/issues/102

Fix update command when there are no plugins

---

README.md

I'll have to do a proper rewrite of the readme at some point.
Closes #13

List changes from zgen in readme

---

zgen.zsh

List of supported startup files:
http://zsh.sourceforge.net/Intro/intro_3.html

Compile zsh startup files in recursive search

---

zgen.zsh

Fix oh-my-zsh/prezto default branches

---

zgen.zsh

If the plugin wants to autoload a function it has to add itself to
`fpath`. Ideally the plugin manager should take care of this.
Now zgenom modifies the fpath before sourcing the plugin. To keep consistency, the order of fpaths is now inverted since now the first
`load` is added the first instead of prepended at the first position.
Closes https://github.com/tarjoilija/zgen/issues/105

Add fpath before sourcing the plugin

---

zgen.zsh

Before a folder was named `user/repo-branch`.
Given the user `jane-doe`, repo `my-plugin` and branch `the-branch` this
folder would be created:
`jane-doe/my-plugin-the-branch`
There is no way to parse the branch from the folder name.
With the new format it is named `jane-doe/my-plugin/the-branch` making
it easy to parse since slashes are escaped.
The next time after `zgenom reset` the repos will be moved
automatically.

Improve folder structure

---

zgen.zsh

Fix zgenom clean to ignore git submodules

---

functions/zgenom-autoupdate

Fix autoupdate with noclobber set

---

README.md
functions/_zgenom
functions/zgenom-autoupdate

It can now be disabled using `--no-background`.

Make --background default for autoupdate

---

functions/zgenom-save
zgenom.zsh

- The reset would only happen for the next shell
- The reset would load plugins twice (init.zsh and .zshrc)

Fix reset on change

---

functions/zgenom-autoupdate

Fix autoupdate not sourcing .zshrc

---

README.md

Move Migration from zgenom out of the fold

---

functions/zgenom-load

Fix local plugin not detecting `functions` folder

---

README.md

Fix wrong word in readme

---

functions/zgenom-update

Fix markdirs interfering with `zgenom update`

---

functions/zgenom-update

This checks for non empty directories and includes the nullglob
modifier.

Strengthen `zgenom update` git directory finding

---

functions/zgenom-autoupdate

Overwrite noclobber for autoupdate log

---

README.md

Make use of `zgenom compile $ZDOTDIR` clearer

---

README.md

Update description of default `$ZGEN_DIR`

---

functions/_zgenom
functions/zgenom-autoupdate

Add --silent to mute output of autoupdate

---

README.md
functions/_zgenom
functions/zgenom-clone
functions/zgenom-load
functions/zgenom-update

Fixes #144
Useful to fix breakages or to stick to audited versions of a plugin

Support pinning to specific commits
