zgenom.zsh

When ~/.zgen exists it still defaults to ~/.zgen.
Closes https://github.com/tarjoilija/zgen/issues/86

Default ZGEN_DIR to cloned location instead of ~/.zgen

---

zgen.zsh

Zgen save would ignore all flags and the custom directory. When
providing a custom path it would always be created as ~/.zcompdump.
Only subsequent shells would create the correct zcompdump as they
recreate it with `compinit -C ...` where the path would be correctly
inserted but the flags would be completely ignored.

Fix creating compinit with custom flags

---

_zgen
zgen.zsh

It compiles *.zsh, *.sh and zcomdump*, as well as all files with zsh
shebang (`#!...zsh`).
In these paths:
- zgen source files
- plugin files
- zcompdump (if custom path or ~/.zcompdump*)
This also adds `zgen compile <path>` to the api.
Closes https://github.com/tarjoilija/zgen/issues/92

Compile files when zgen save is called

---

zgen.zsh

In my opinion the `load` syntax is a bit overloaded already. Also adding
other commands like `bin` would have to implement this in multiple
places.
This can however be achieved like this:
```zsh
zgen clone <repo> --no-submodules
zgen load <repo>
```
Closes https://github.com/tarjoilija/zgen/issues/129

Allow to clone without submodules

---

README.md
zgenom.zsh

By default, clone plugins and themes in a separate subdirectory tree in `$ZGEN_SOURCE` instead of at the top level.
This keeps the zgenom source directory clean and makes it easier to do a full reset of all clones by deleting `$ZGEN_SOURCE/sources`

Make plugins/themes clone into $ZGEN_SOURCE/sources instead of $ZGEN_SOURCE.

---

README.md
zgen.zsh

How it works:
Repos without a branch specified will get the *magic branch* ___. When
updating a repo with this branch the head of origin will be updated.
When this fails (the head branch isn't known locally) the error message
is parsed for the new heads name. Then the new head is fetched and
origin updated again.
Afterwards the symbolic ref for origins head is resolved and checked if
it is the current branch.
If not the new branch is deleted (in case it existed), the new head is
checked out and the old head branch is deleted.
Closes #16

Add support for default branches

---

zgen.zsh

`zgen.zsh` would not source `zgenom.zsh` correctly since I forgot to update the name.

Fix not setting ZGEN_DIR correctly for zgen.zsh

---

.gitignore
zgen.zsh

After merging #18 it doesn't make too much sense add bins to the sources
folder. So the bins will now be stored in the zgenom project path.
This was the initial idea as well but was a bit complicated since a
github username could be `bin` as well.
When updating it may result in residual data in `$ZGEN_DIR/_/bin`. Since
there are only links stored it should be negligible. Please remove this
folder manually if it bothers you.

Move bins from sources/_/bin to bin

---

zgen.zsh

The check for compiled zcompdump didn't work for $HOME/.zcompdump.
Hopefully closes #28

Fix compiling $HOME/.zcompdump*

---

zgen.zsh

This was introduced in #26
Closes #28

Fix compiling ZGEN_DIR twice if in ZGEN_SOURCE

---

zgen.zsh

This should silence most errors while compiling.
Closes #31

Don't expand aliases when compiling

---

zgen.zsh

Initially this was added as a way to provide a way to add
`$ZGEN_SOURCE/bin` manually (at the position the user wants). This
setting complicates things and I'm not really sure it made sense in the
first place.
If you relied on this setting please submit an issue.

Remove ZGENOM_ADD_PATH

---

README.md
zgen.zsh

The Zsh Plugin Standard defines that a plugin manager should
automatically source the bin folder of the plugin.
Zgenom supports this by setting `ZGENOM_AUTO_ADD_BIN=1` which is 0 by
default.

Support to automatically add ./bin to PATH

---

README.md
functions/_zgen
zgen.zsh

This removes all repos which aren't used by the current configuration.
Use this to quickly get rid of all unused plugins
Closes https://github.com/tarjoilija/zgen/issues/103

Add zgenom clean

---

zgen.zsh

When `zsh -n $file` fails compiling the file file fail as well.
Only `*.sh` files are checked because files for zsh (extension or
shebang) should be working.
Closes #45

Don't compile unreadable files

---

zgen.zsh

Set `ZGENOM_AUTO_COMPILE=1` to compile the ZDOTDIR or the default
startup files whenever a new init file is created.

Add option to automatically compile ZDOTDIR

---

README.md

- Forked autoupdate-zgen to autoupdate-zgenom - the new plugin no longer tries to be backward compatible with zgen. Update references accordingly
- Update the zsh-quickstart-kit entry

Update autoupdate-zgen references to autoupdate-zgenom

---

README.md

Instead of loading the `src` folder manually zsh-completions has a plugin file which adds the correct path. When providing a folder to zgenom it will add the path to `fpath` which is the wanted behavior in this case. It also iterates over all files which match `*.sh` and will source them. Since zsh-completions has files like `_rmlint.sh` in this folder they're matched and sourced which is the not wanted behavior - resulting in an error. While this could be fixed by checking for `*.sh` and exclude `_*.sh` files I'm not sure if this is a so widely popular naming scheme that it would not break another plugin. Closes #59

Update readme to show proper loading of zsh-completions

---

zgen.zsh

If such a file needs to be sourced please do so manually using this command: `zgenom load <plugin> path/to/_file.sh`.
Closes #59

Don't source files which start with `_`

---

README.md
zgen.zsh

- Add folding
- Reorder sections
- Show how to use `zgenom compile`
- Remove automatically compiling ZDOTDIR (please use `zgenom compile` as shown in the readme)
- Show how to load plugins conditionally
- Add hints how to use zgenom more dynamically*
\* This is not an official feature. It's rather a byproduct.

Improve Readme

---

.gitignore
README.md
functions/__zgenom_autoupdate
functions/zgenom-autoupdate
functions/zgenom-selfupdate
functions/zgenom-update

These backups will run fully in the background so you won't any slowdown in your startup time.
When the update is complete and you start a new shell everything is prepared so you don't have to wait then either.
When starting a new shell after a completed update you will get a log showing you what happened in the background.

Introduce automatic background updates

---

functions/zgenom-ohmyzsh

Regenerating the init file was causing an error message due to there being an extra underscore in "__zgenom_clone_dir" so I removed the underscore and it's been fixed

Removed extra underscore causing error message

---

README.md
functions/__zgenom_autoupdate
functions/zgenom-autoupdate

This reduced the startup time of autoupdate without `--background`
around ~~7ms~~ 14ms for me.
Now the main culprit is checking whether the current user is the
zgenom_owner ~~and if a update is currently running (in another shell)~~.

Improve performance of autoupdate checking

---

README.md
commands.txt
functions/_zgenom
functions/zgenom-api
functions/zgenom-help
zgenom.zsh

Extensions is far stretched. By design `zgenom` will work with every
function matching `zgenom-*`. This pr adds a safe way to call some
portions of the internal api and allows to add command descriptions to
help and completion using `$ZGENOM_EXTENSIONS`. Also defining
`_zgenom_*` will add completion for the subcommand well.

Allow extensions to integrate into zgenom

---

zgenom.zsh

As seen in #72 Alias tip hints to use zgen instead of zgenom.

Fix Alias tip hinting to use zgen

---

README.md
functions/_zgenom
functions/zgenom-load
functions/zgenom-ohmyzsh

Instead of always sourcing all matching files in the given path.
`zgenom load --completion` or `zgenom ohmyzsh --completion` will do
this.
Closes #82

Allow adding just completions

---

README.md

Fixes a few links that were pointing to the now defunct zdharma org and website

zdharma is dead, long live zdharma-continuum

---

README.md
functions/_zgenom
functions/zgenom-list

Also fix an error in the readme showing `load` instead of `bin`.
Closes #88

Refactor zgenom list to use --bin and --init

---

README.md

This allows
```zsh
zgenom load zsh-users/zsh-history-substring-search
zgenom eval <<EOF
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
EOF
zgenom eval --name zoxide <<(zoxide init zsh)
```
Closes #84

List zgenom-ext-eval

---

functions/zgenom-autoupdate

Hopefully this fixes an issue with `~` expansion in some cases.
Closes #92

Use absolute path for sourcing zshrc

---

functions/__zgenom

When zgenom was fully loaded (`__zgenom`) localoptions and extendedglob
was being set to find all autoloaded functions.
This localoptions would prevent setting any options from the file
sourced by this first call.
So when for example the first call was `zgenom load my/plugin`
`my/plugin` wouldn't be able to set any options. This would only occur
in the first shell after `zgenom reset` since this issue would not
persist in the generated `init.zsh`.
Closes #101

Fix localoptions being set for first zgenom call

---

README.md
functions/_zgenom
functions/zgenom-compile
functions/zgenom-save

Those are the same options used by `zcompile`. These options are only
passed through.
Closes #102.

Allow specifying options for zgenom compile

---

functions/zgenom-compile

This issue was introduced in #106.

Fix not compiling files when no zwc exists

---

functions/zgenom-compile

While I don't think this is needed it is easier to allow compiling
multiple files with one statement than preventing completion from only
completing exactly one file/path.

Allow compiling multiple paths with one call

---

functions/zgenom-clone
functions/zgenom-save

Thanks for reviving zgen and adding new features!
I tried migrating from zgen to zgenom and had a few hiccups due to the fact that zgenom does not take into account spaces in file paths when migrating or loading plugins. I'm on macOS and try to keep things organized into directories according to how macOS stores configuration files for programs (e.g. `~/Library/Application Support`) so that my home directory is not cluttered with hidden files and directories specific to each program. Because of this I've set `$ZGEN_DIR` to `~/Library/Application Support/net.sourceforge.Zsh/zgen` (`net.sourceforge.Zsh` is supposed to mimic how other applications name their configuration directories, for example there is also `com.microsoft.OneDrive` and `com.apple.spotlight`). The space in `Application …

Fix bug where loading and migrating plugins with spaces in them fails

---

README.md
commands.txt
functions/zgenom-apply
functions/zgenom-compdef
functions/zgenom-save
zgenom.zsh

This solves the issue that some plugins use `compdef` but zgenom does
`compinit` after loading all plugins.

Add zgenom compdef

---

README.md

chore: use plugins/macos instead of plugins/osx

---

functions/zgenom-load
functions/zgenom-save

fix the bug mentioned in romkatv/gitstatus#168.
we'll get the error something like
```
blahblah...: not valid in this context: _gitstatus_plugin_dir/Users/javenwang/.zgenom/sources/romkatv/gitstatus-master/gitstatus.plugin.zsh
```
when `zgenom load romkatv/gitstatus` in `.zshrc`.

fix sourcing plugins

---

README.md
zgen.zsh
zgenom.zsh

If you currently use `zgen` instead of `zgenom` you now have to source
`zgen.zsh` instead of `zgenom.zsh`.

Breaking: Move zgen compatibility into `zgen.zsh`

---

functions/zgenom-compile

Also move `if` logic to the glob itself.
~*.zwc -> only when it does not match *.zwc
(.)    -> only match files

Don't compile files in .git folders

---

README.md

It seems like that GitHub will generate heading link in lower-case. So I fixed all the heading links to lower-case.

fix: fix heading links in README.md

---

functions/zgenom-compile

Fixes issue #156
This also fixes an issue with the existing glob pattern, it turns out that it was still iterating over all the files in '.git' directories.  I won't take any credit here (except for noticing it in the logging), ChatGPT explained everything and helped me write the proper code.
I generalized the directory exclusions so there is a list of directories that are recursively excluded.  I also generalized the file extension exclusion from only `zwc` to exclude a bunch of obviously non-zsh files (as well as zwc files).  Although reading the first line doesn't take a ton of time, it's still not as fast as skipping the files entirely.  The net result is a substantial reduction in the time it takes to run the compile phase.  Here are numbers:
tl;dr:  Time to run `zgenom-compile` was …

Exclude test dirs and specific file extensions from zsh compilation (#156)
